---
- name: Download Go
  get_url: url=http://golang.org/dl/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz
           dest=/usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz

- name: Extract and install Go
  command: tar -C /usr/local -xzf /usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz
           creates=/usr/local/bin/go

- name: Symlink Go into /usr/local/bin
  file: src=/usr/local/go/bin/{{ item }} dest=/usr/local/bin/{{ item }} state=link
  with_items:
    - go
    - godoc
    - gofmt

- name: Install Godep
  command: go get github.com/tools/godep
           creates={{ golang_path }}/bin/godep
  environment: env

- name: Enable GOPATH on login
  template: src=gopath.sh.j2 dest=/etc/profile.d/gopath.sh
